#设置对输出参数的格式化
#spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

#北京时间相对伦敦有8个小时时差所以使用GMT+8，这样才能正常显示日期
#spring.jackson.time-zone=GMT+8

#设置对输入参数的格式化，这样后台的接口就可以接收Date类型
#spring.mvc.date-format=yyyy-MM-dd

#设置端口号
#server.port=8888
#server.servlet.context-path=/

#配置自己的文件服务器地址
#fileServer.path=http://image.qf.com

#配置自己的邮箱服务器地址
#emai1Server.path=http://email.qf.com


#配置系统相关信息
#resource.imageServer = http://images.hgz2.com
#resource.emailServer = http://email.hgz2.com

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    date-format: yyyy-MM-dd
  profiles:
    active: dev
server:
  port: 8888

#决定读取那套文件(激活节点)